### ISSUE TITLE
Field "isMonitored" of type builtins.bool is missing in snyk.models.Project instance

### ISSUE THREAD

**Issue by pohly** [snyk-labs/pysnyk#106]
This is with pysnyk 0.6.1 installed via pip3.

```
$ python3 examples/api-demo-1-list-projects.py --orgId=....
Traceback (most recent call last):
  File "examples/api-demo-1-list-projects.py", line 23, in <module>
    for proj in client.organizations.get(org_id).projects.all():
  File "/home/pohly/.local/lib/python3.7/site-packages/snyk/managers.py", line 168, in all
    return self._query()
  File "/home/pohly/.local/lib/python3.7/site-packages/snyk/managers.py", line 159, in _query
    projects.append(self.klass.from_dict(project_data))
  File "<string>", line 106, in from_dict
mashumaro.exceptions.MissingField: Field "isMonitored" of type builtins.bool is missing in snyk.models.Project instance
```

Enabling logging shows that the `GET /api/org/.../projects HTTP/1.1` succeeded.

**Comment by pohly** [comment]
I'm running this against my company's Snyk installation, not the public Snyk server.
