### ISSUE TITLE
pysnyk doesn't work with Python 3.10

### ISSUE THREAD

**Issue by tongpu** [snyk-labs/pysnyk#126]
After updating from Python 3.9 to Python 3.10 I've ran into the issue that my pysnyk based scripts wouldn't work anymore, e.g.:

```console
$ ./list-vulnerabilities.py --from 2021-12-14 --to 2021-12-15  
Traceback (most recent call last):
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/./list-vulnerabilities.py", line 7, in <module>
    import snyk
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/.venv/lib/python3.10/site-packages/snyk/__init__.py", line 23, in <module>
    from .client import SnykClient
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/.venv/lib/python3.10/site-packages/snyk/client.py", line 10, in <module>
    from .models import Organization, Project
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/.venv/lib/python3.10/site-packages/snyk/models.py", line 6, in <module>
    from mashumaro import DataClassJSONMixin  # type: ignore
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/.venv/lib/python3.10/site-packages/mashumaro/__init__.py", line 4, in <module>
    from mashumaro.serializer.json import DataClassJSONMixin
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/.venv/lib/python3.10/site-packages/mashumaro/serializer/json.py", line 28, in <module>
    class DataClassJSONMixin(DataClassDictMixin):
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/.venv/lib/python3.10/site-packages/mashumaro/serializer/base/dict.py", line 21, in __init_subclass__
    raise exc
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/.venv/lib/python3.10/site-packages/mashumaro/serializer/base/dict.py", line 17, in __init_subclass__
    builder.add_to_dict()
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/.venv/lib/python3.10/site-packages/mashumaro/serializer/base/metaprogramming.py", line 330, in add_to_dict
    pre_serialize = self.get_declared_hook(__PRE_SERIALIZE__)
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/.venv/lib/python3.10/site-packages/mashumaro/serializer/base/metaprogramming.py", line 196, in get_declared_hook
    if type_name(cls) != DataClassDictMixinPath:
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/.venv/lib/python3.10/site-packages/mashumaro/meta/helpers.py", line 28, in type_name
    if is_generic(t):
  File "/home/lukasgr/Documents/Vontobel/git/snyk-helpers/.venv/lib/python3.10/site-packages/mashumaro/meta/helpers.py", line 54, in is_generic
    raise NotImplementedError
NotImplementedError
```

I was able to fix it by updating the `mashumaro` dependency to `mashumaro = "^2.0"` in `pyproject.toml`, but wasn't sure how your release processes work, so I didn't provide a PR.

**Comment by w0rmr1d3r** [comment]
Hi @tongpu , I'm having the same issue, but I realize that in here:
https://pypi.org/project/pysnyk/0.6.3/
They say they support from Python 3.6 up to 3.9, I guess version 3.10 is not supported yet 😞
