### ISSUE TITLE
Performing a simple get orgs causes [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by marcellusfelisbret** [snyk-labs/pysnyk#156]
import snyk

client = snyk.SnykClient(Secrettoken)
org=client.organizations.all()
print(org)
exit()

raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='snyk.io', port=443): Max retries exceeded with url: /api/v1/orgs (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

**Comment by husseyd** [comment]
Seeing a similar error for self-signed certificates:

```During handling of the above exception, another exception occurred:
68Traceback (most recent call last):
69  File "/home/gitlab/report.py", line 287, in <module>
70    main()
71  File "/home/gitlab/report.py", line 270, in main
72    projects_list = build_projects_list(_projects)
73  File "/home/gitlab/report.py", line 19, in build_projects_list
74    _project_list.append(build_project_dict(project))
75  File "/home/gitlab/report.py", line 52, in build_project_dict
76    for vuln_object in project_object.issueset_aggregated.all().issues:
77  File "/home/gitlab/.local/lib/python3.10/site-packages/snyk/managers.py", line 408, in all
78    return self.filter()
79  File "/home/gitlab/.local/lib/python3.10/site-packages/snyk/managers.py", line 438, in filter
80    resp = self.client.post(path, post_body)
81  File "/home/gitlab/.local/lib/python3.10/site-packages/snyk/client.py", line 77, in post
82    resp = retry_call(
83  File "/home/gitlab/.local/lib/python3.10/site-packages/retry/api.py", line 101, in retry_call
84    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
85  File "/home/gitlab/.local/lib/python3.10/site-packages/retry/api.py", line 33, in __retry_internal
86    return f()
87  File "/home/gitlab/.local/lib/python3.10/site-packages/snyk/client.py", line 66, in request
88    resp = method(url, headers=headers, json=json)
89  File "/home/gitlab/.local/lib/python3.10/site-packages/requests/api.py", line 115, in post
90    return request("post", url, data=data, json=json, **kwargs)
91  File "/home/gitlab/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
92    return session.request(method=method, url=url, **kwargs)
93  File "/home/gitlab/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
94    resp = self.send(prep, **send_kwargs)
95  File "/home/gitlab/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
96    r = adapter.send(request, **kwargs)
97  File "/home/gitlab/.local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
98    raise SSLError(e, request=request)
99requests.exceptions.SSLError: HTTPSConnectionPool(host='snyk.io', port=443): Max retries exceeded with url: /api/v1/org/<REDACTED>/project/<REDACTED>/aggregated-issues (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))```

**Comment by ig596** [comment]
@marcellusfelisbret Support for setting the flag on if you want to enable SSL certificate validation has been added to the client in #155. Please mark this issue as closed/resolved.

**Comment by marcellusfelisbret** [comment]
Support for setting the flag on if you want to enable SSL certificate validation has been added to the client in https://github.com/snyk-labs/pysnyk/pull/155. Please mark this issue as closed/resolved.
